interface GitHubPRDiff {
  diff: string
  additions: number
  deletions: number
  changedFiles: number
}

export async function getPullRequestDiff(
  owner: string,
  repo: string,
  prNumber: number,
  token: string
): Promise<GitHubPRDiff> {
  // Get the diff
  const diffResponse = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/pulls/${prNumber}`,
    {
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github.diff',
        'X-GitHub-Api-Version': '2022-11-28',
      },
    }
  )

  if (!diffResponse.ok) {
    throw new Error(`Failed to fetch PR diff: ${diffResponse.status}`)
  }

  const diff = await diffResponse.text()

  // Get PR metadata for stats
  const prResponse = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/pulls/${prNumber}`,
    {
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
    }
  )

  if (!prResponse.ok) {
    throw new Error(`Failed to fetch PR metadata: ${prResponse.status}`)
  }

  const pr = await prResponse.json() as {
    additions: number
    deletions: number
    changed_files: number
  }

  return {
    diff,
    additions: pr.additions,
    deletions: pr.deletions,
    changedFiles: pr.changed_files,
  }
}

export async function createPullRequestReview(
  owner: string,
  repo: string,
  prNumber: number,
  body: string,
  token: string
): Promise<void> {
  const response = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/pulls/${prNumber}/reviews`,
    {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github+json',
        'Content-Type': 'application/json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
      body: JSON.stringify({
        body: `## AI Code Review\n\n${body}\n\n---\n*This review was generated by [itay.dev](https://itay.dev) to help you learn and improve.*`,
        event: 'COMMENT', // COMMENT, APPROVE, or REQUEST_CHANGES
      }),
    }
  )

  if (!response.ok) {
    const error = await response.text()
    throw new Error(`Failed to post review: ${response.status} - ${error}`)
  }
}
